In [1]:
import pandas as pd

from sentence_transformers import SentenceTransformer

/opt/homebrew/anaconda3/envs/ml/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_csv("PolicyPulse_Cleaned.csv")

df.head()

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...","Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,"Social Welfare, Financial Assistance, Deceased..."

In [ ]:
# Create Combined Text
df["combined_text"] = (
    df["scheme_name"].fillna("") + " " +
    df["details"].fillna("") + " " +
    df["benefits"].fillna("") + " " +
    df["eligibility"].fillna("") + " " +
    df["application"].fillna("") + " " +
    df["documents"].fillna("") + " " +
    df["tags"].fillna("")
)

In [4]:
df.head()

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,tags,combined_text
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...","Missing, Fisherman, Relief, Financial Assistan...","""Immediate Relief Assistance"" under ""Welfare a..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,"Trainings, Financial Assistance, AICTE",AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCH...
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,"Building Worker, Construction Workers, Unregis...",Burial and Ex-gratia Payment Scheme in Case of...
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,"Goods And Services Marketing, Turnkey Projects...",Consortia & Tender Marketing Scheme Promotion ...
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,"Social Welfare, Financial Assistance, Deceased...",Garuda Scheme for Funeral Expense Andhra Prade...

In [ ]:
# Download Embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 10009.81it/s]

In [6]:
# Generate Embeddings
embeddings = model.encode(
    df["combined_text"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches: 100%|██████████| 105/105 [00:59<00:00,  1.76it/s]

In [7]:
print(embeddings.shape)

(3356, 384)

In [8]:
print(embeddings[0])

[-6.09565414e-02  7.46017098e-02 -5.63627928e-02 -4.95956801e-02
 -5.66768795e-02  1.45071866e-02  1.68476198e-02  7.14573190e-02
 -4.13008556e-02  4.27415798e-04  1.06503725e-01 -9.90639180e-02
  2.15612147e-02 -1.67684592e-02  2.45520119e-02  3.46584134e-02
 -1.02936877e-02 -4.37999517e-02 -5.09557202e-02  3.39429751e-02
 -6.37481827e-03  2.87512201e-03 -1.29916325e-01 -1.40412208e-02
  4.10932675e-02  3.14343981e-02  1.58338379e-02 -9.99972969e-03
  1.88580714e-02 -2.33207047e-02  1.06918849e-01  4.96908613e-02
  1.42949829e-02 -4.89672720e-02  6.99313870e-03  5.68024851e-02
 -7.24118128e-02  3.87185179e-02 -4.84073646e-02 -5.44824684e-03
 -2.03936198e-03  3.97648551e-02 -2.16669124e-03 -1.49704413e-02
  4.41385359e-02 -2.40411889e-02 -2.24730372e-02  9.86562148e-02
 -3.28049324e-02 -3.70787047e-02 -5.46703755e-04  1.11490767e-02
  3.24521400e-02  1.06010653e-01 -2.72440072e-03 -4.94576804e-02
  5.88447182e-03 -2.75179744e-02 -8.34626183e-02 -6.45938143e-02
 -5.75321168e-03  3.75615731e-02 -1.96322333e-02 -4.56882715e-02
 -7.26072676e-03 -2.43792608e-02  4.16814312e-02 -8.61902442e-03
  1.28835691e-02  2.45750672e-03 -2.25411989e-02 -6.93613961e-02
 -1.21589657e-02 -6.57547712e-02 -3.37531976e-02 -2.51327865e-02
  7.00210854e-02  1.75358802e-02 -1.38759334e-02 -6.37865216e-02
 -3.56162675e-02  2.89326860e-03  3.56598981e-02 -3.19804326e-02
 -1.14382599e-02  2.33216397e-02 -2.92572100e-02  6.54202595e-05
  1.38825281e-02 -4.16403562e-02  4.03982103e-02 -1.02434969e-02
  8.09104815e-02 -4.54901382e-02 -1.14441325e-04  2.52970662e-02
  9.93367005e-03 -3.88891064e-02 -5.88244684e-02  6.75967783e-02
  3.39367776e-04 -1.30804833e-02 -1.83426142e-02 -5.35807312e-02
 -1.31156035e-02 -1.89436916e-02 -1.63281634e-02  4.20724005e-02
  4.47761081e-02 -8.73302370e-02 -9.81116220e-02  2.37690825e-02
 -3.58657143e-03  2.48269700e-02 -9.71727371e-02  7.00460747e-02
 -2.95480769e-02 -1.46081555e-03  7.58405328e-02 -4.04060706e-02
  6.32950217e-02  1.13844045e-01  1.14005720e-02 -1.59601634e-03
  1.36536295e-02 -3.64807136e-02  2.23956406e-02  1.83804595e-33
 -6.50977120e-02  1.66144129e-02 -2.54655015e-02 -4.54803407e-02
  9.85398050e-03 -8.91275033e-02 -3.32926996e-02  1.72920376e-02
  4.13914844e-02  4.54987101e-02 -4.32260567e-03  3.29685360e-02
  1.14833293e-02 -1.35525391e-02 -8.01824927e-02 -8.55758116e-02
  1.65401734e-02  5.42845502e-02  5.01830876e-02  6.09146655e-02
  3.09352633e-02 -3.01767793e-02  4.47505154e-02  3.17424797e-02
  3.41557041e-02  3.07530705e-02  4.63508219e-02  7.50621874e-03
  5.71990060e-03  1.27415042e-02  8.12350661e-02  2.76091173e-02
  1.79941133e-02 -1.50313616e-01 -3.31428535e-02 -6.16478026e-02
  8.26069713e-02 -3.36122289e-02 -4.87443618e-02 -3.73320803e-02
 -8.25126171e-02  2.96054147e-02  5.91521263e-02 -2.33054347e-02
 -4.55476753e-02 -5.34326024e-02  7.20277950e-02  5.45326509e-02
 -1.40078394e-02  1.29446104e-01 -3.95095628e-03 -4.35788184e-02
 -3.23905908e-02 -1.48916421e-02 -5.85276820e-02 -2.48362217e-02
 -5.51761538e-02  1.53342094e-02  1.76482871e-02  1.19425857e-03
  4.19064611e-02 -1.31681904e-01 -2.26054732e-02  2.27096807e-02
 -6.48707151e-02  3.20875980e-02  4.88173142e-02 -3.36622149e-02
  1.41736271e-03 -2.50184089e-02 -1.14992872e-01 -1.71846543e-02
  4.05710787e-02  4.73381728e-02 -5.39452881e-02 -1.73011224e-03
  6.34614974e-02  2.79771108e-02  3.39549966e-02  1.96479019e-02
 -6.23731613e-02 -4.44219913e-03  4.68838774e-02  2.78703980e-02
  9.04714242e-02  8.65781009e-02  7.32894009e-03 -4.67503369e-02
 -1.88514479e-02  1.33388750e-02 -4.54588830e-02  3.12662683e-02
  5.01231588e-02  9.89233237e-03  1.77070662e-01 -2.92732458e-33
 -1.57269016e-02 -2.02989075e-02 -7.66548216e-02 -3.28114033e-02
  3.95002142e-02  1.51052056e-02  5.98198995e-02  4.37076688e-02
  4.39700149e-02  3.74790095e-02 -1.55136943e-01  4.69712056e-02
  2.95484252e-02  3.33758891e-02 -5.44667803e-02  3.80947404e-02
  1.27843041e-02  1.05342651e-02 -1.84723586e-02  3.13693769e-02
 -6.67520752e-03  1.12893112e-01  2.91236248e-02 -3.31957801e-03
 -8.64777947e-04  1.28735825e-01 -2.73081567e-02  1.56315099e-02
 -8.67174268e-02  4.99645853e-03  1.04454942e-02 -8.10412839e-02
 -6.08201101e-02 -2.02372763e-03 -6.08568266e-02 -6.19722903e-02
  2.36576572e-02  5.15637025e-02 -7.31712207e-02  6.23305850e-02
  6.86788559e-02  1.12088455e-03 -2.27872841e-02  3.45682129e-02
  5.40795876e-03 -1.50112305e-02  4.26629595e-02 -2.94440072e-02
  4.02313210e-02  1.34736095e-02  4.58248295e-02  2.16357186e-02
  1.51120797e-01  7.98832476e-02  2.93283705e-02 -6.91860309e-03
  8.25531036e-02 -7.09094927e-02 -1.87043101e-02 -5.93938492e-02
 -1.11016678e-02  3.08552105e-02 -1.77349634e-02  1.21480264e-01
  3.70734483e-02 -1.67005342e-02 -1.16454568e-02 -6.85691163e-02
  6.35915920e-02 -7.25421160e-02  3.51654319e-03 -3.59952189e-02
 -3.65633890e-02 -9.51749608e-02  7.42202848e-02  1.24253139e-01
 -6.24494180e-02 -3.32637578e-02  3.56649160e-02 -2.64810752e-02
 -7.46394843e-02 -6.53105834e-03  3.84457298e-02 -5.62956668e-02
 -4.00847904e-02 -1.00959383e-01  4.88302708e-02 -6.86305687e-02
  1.00987442e-01 -1.00195343e-02 -6.16377443e-02  6.54066131e-02
  6.56048506e-02  2.98849996e-02  1.57342218e-02 -5.26635375e-08
  5.31424060e-02 -3.46925631e-02 -4.85650413e-02 -2.57402919e-02
  1.70968659e-02 -9.93692651e-02 -1.25184685e-01  2.00623758e-02
 -6.93152025e-02  7.56742491e-04  5.06213345e-02  5.09919897e-02
  7.63853174e-03 -4.80194613e-02  2.10497892e-04 -5.78570925e-02
  4.82216477e-02 -3.44956182e-02 -1.05698027e-01 -9.58553236e-03
 -1.73688494e-02  3.65229659e-02 -7.13468203e-03 -4.49762419e-02
  2.07957774e-02 -1.36763472e-02  9.00322124e-02  7.74356052e-02
  6.05232269e-02 -2.15791762e-02 -2.87198741e-02  2.92303432e-02
  5.80716878e-04  2.74193324e-02 -1.06617091e-02  4.22256701e-02
 -1.13117363e-04  4.85193767e-02 -8.02552421e-03  3.53125110e-02
 -3.65101136e-02 -1.75079368e-02  1.64229926e-02  1.69560947e-02
 -1.25065940e-02 -2.31743022e-03 -1.33760706e-01 -1.44521305e-02
  1.22361667e-02 -1.23460703e-01 -6.43318966e-02 -3.62930470e-03
 -7.92561378e-03  4.27150168e-02 -1.97238941e-02  3.90726626e-02
  3.74502433e-03 -2.93524247e-02 -3.23587321e-02  2.87221260e-02
  5.01005091e-02 -4.32390012e-02 -5.74936569e-02 -3.36118303e-02]

In [ ]:
# Save the folder in NP format 
import numpy as np

np.save("scheme_embeddings.npy", embeddings)

In [10]:
# Verification
loaded = np.load("scheme_embeddings.npy")

print(loaded.shape)

(3356, 384)